### ISSUE TITLE
Install Error on 2 separate sites

### ISSUE THREAD

**Issue by Sez0105** [veda-consulting/uk.co.vedaconsulting.gdpr#134]
Issue on installing GDPR 2.6 on 2 separate sites. Both seem to show same final issue 'SLA' issue. Anyone else with same issue or know why?

#0 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(292): CRM_Core_ManagedEntities->onApiError("CiviRuleCondition", "create", (Array:3), (Array:5))
#1 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(196): CRM_Core_ManagedEntities->disableEntity(Object(CRM_Core_DAO_Managed))
#2 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(123): CRM_Core_ManagedEntities->reconcileDisabledModules()
#3 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(403): CRM_Core_ManagedEntities->reconcile()
#4 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Extension/Manager.php(332): CRM_Core_Invoke::rebuildMenuAndCaches(TRUE)
#5 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(205): CRM_Extension_Manager->disable((Array:1))
#6 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(345): CRM_Admin_Form_Extensions->postProcess()
#7 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(164): CRM_Core_Form->mainProcess()
#8 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#9 /home/cvsceorg/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#10 /home/cvsceorg/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#11 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("next")
#12 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(395): CRM_Core_Controller->run()
#13 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(174): CRM_Core_Page_Basic->edit(64, NULL)
#14 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(125): CRM_Core_Page_Basic->run()
#15 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#16 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
#17 /home/cvsceorg/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#18 /home/cvsceorg/public_html/sites/all/modules/civicrm/drupal/civicrm.module(482): CRM_Core_Invoke::invoke((Array:3))
#19 [internal function](): civicrm_invoke("admin", "extensions")
#20 /home/cvsceorg/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#21 /home/cvsceorg/public_html/index.php(21): menu_execute_active_handler()
#22 {main}

**Comment by Upperholme** [comment]
From the backtrace you've posted it looks like CiviRules might be the cause of the issue? Maybe try disabling the CiviRules extension before installing GDPR and see if that helps?

**Comment by veda-consulting** [comment]
@Sez0105 if you could confirm that would be great

Thanks @Upperholme

**Comment by Sez0105** [comment]
@Upperholme @veda-consulting this didn't work- we disabled and tried updating the civirules on the site but it caused further issues on the site. Our developer is looking into upgrading the site completely now, but is having issues currently because of other extensions/ customisations the site has, not sure if this is what is causing the issue with the GDPR module on the site I posted the back trace for. 

The other site doesn't have civirule so this can't be the reason for the fail on 2nd site. I can post the back trace for the 2nd site?

Thanks

**Comment by Sez0105** [comment]
Hi,
This issue is still not resolved and another site we support has a simular issue now also- I have upgraded there version of the module from version 1 to version 2.6, they are now getting the same "'SLA  Acceptance' is not a valid option for field activity_type_id"-

**Comment by cmolava** [comment]
There's a  general pattern for these kind of errors:

1) On installation  the gdpr extension registers entities with Civi.
2) Civi rebuilds the list of managed entities provided by other components and extensions.
3) While building the list, Civi throws an exception because it has a problem with another extension. There could be a number of reasons for this. Sometimes upgrading or running pending schemas on the extension can fix it. A common one is an empty or duplicate value for domain on a table. It also happens if Civi Core's schema upgrade hasn't completed. 
4) Because the gdpr extension has not been able to install the data required for it to run, more errors are caused.  

In your first case @Sez0105, the backtrace comes from an error at (3) (from CiviRules) whereas the 
 "'SLA Acceptance' is not a valid option for field activity_type_id" is at (4).

If it is a new installation then think the best thing to do is to uninstall gdpr, resolve the problem with the other extension, then reinstall gdpr. 

However I noticed in the last install you mentioned an upgrade from 1 to 2.6.  The issue here might be that it was a very early version which did not need to create the new data on installation, so it may suffice to reinstall. (In any case, test on a sandboxed environment first).


Note: uninstalling gdpr doesn't remove all it's data - but there is a sql file that does so: https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/blob/master/sql/gdprRemoveAllData.sql

**Comment by mikantchap** [comment]
Thanks for this - very useful. After disabling the GDPR extension, I was still getting a $ManagedEntities_failed error on doing civicrm/clearcache. Once I had fixed that, I was able to uninstall + install version 2.6 OK.

**Comment by TerryVeda** [comment]
Resolved - see issues 96, 134, 154
