### ISSUE TITLE
GDPR ext: Data Policy .pdf file can not be previewed or downloaded

### ISSUE THREAD

**Issue by alexletizia** [veda-consulting/uk.co.vedaconsulting.gdpr#136]
We have a CiviCRM 5.2.1 on **Wordpress 4.9.6** with GDPR ext. 2.6

When we attach a Policy/Terms .pdf file, it seems to be attached, it is uploaded in 

- https://xxx.example.com/wp-content/uploads/civicrm/persist/contribute/example.pdf

(therefore out of the folder "images") but ... the "Data Policy" link on the Communications preferences page does not work! (it does not open a .pdf preview or not do the download) and redirects to the same page.

The path of "custom file" directory (where we thought that the .pdf files were archived, as in "notes") is correctly configured.

We thought that the problem was this: we know that Wordpress does not have a native module of .pdf preview; then we have installed PDF Embedder; it works correctly on the same Wordpress where CiviCRM is installed but only for "normal posts" with .pdf saved on the "normal" Wordpress Media repository.

**Comment by veda-consulting** [comment]
@rajeshrhino can you take a look please

**Comment by veda-consulting** [comment]
@rajeshrhino ignore, pushed to @mathavanveda

**Comment by mathavanveda** [comment]
Hi @alexletizia ,

Just trying to reproduce the issue, 
When you hover over the "Data policy" link can you be able to see the file path at the bottom of the browser.

(if possible can you please share a screen shot )

**Comment by alexletizia** [comment]
Hi @mathavanveda 

attached a screenshot. 

![gdpr pdf data policy issue](https://user-images.githubusercontent.com/40597363/42029156-ebaeb342-7ace-11e8-84b9-c22ed850cdb6.png)

**Comment by mathavanveda** [comment]
Hi @alexletizia,

Seems there is no Data policy link has been populated in this page. thats why the Link for "Informative
 Privacy" is pointing to same page.

This may be because GDPR data policy settings not configured properly. 

![data policy settings](https://user-images.githubusercontent.com/6152709/42031112-ffbdff20-7acc-11e8-8fb4-f28c1d985ad4.png)

can you please make sure that the data policy file has been attached and able to view/download.
or you can hover over the link which will show the file path 
(https://xxx.example.com/wp-content/uploads/civicrm/persist/contribute/example.pdf)

**Comment by alexletizia** [comment]
The problem is just this! If we try to attach a .pdf like this:

![gdrp civicrm issue 2](https://user-images.githubusercontent.com/40597363/42033117-1703dd08-7adc-11e8-9e76-aa3a7b23c793.JPG)

it will save it in:

https://xxx.example.com/wpcontent/uploads/civicrm/persist/contribute/Informativa_Aruba_SpA.pdf

but then no link will appear! as you can see here:

![gdrp civicrm issue 3](https://user-images.githubusercontent.com/40597363/42033326-d82b5f88-7adc-11e8-8e23-ce2943b849ac.JPG)

**Comment by alexletizia** [comment]
Hi @rsbroughton and @mathavanveda 

We don't use symbolic links:

![issue4](https://user-images.githubusercontent.com/40597363/42043595-1b3585fa-7af7-11e8-9000-e196a5c31089.JPG)

**Comment by Upperholme** [comment]
If I copy the file to wp-content/plugins/files/civicrm/persist/contribute/files/privacy-policy.pdf I still get a 404 when trying to reach it, despite the fact that I can reach other files that have been uploaded to that directory via CiviCRM. Both files have the same permissions

**Comment by alexletizia** [comment]
No, the problem is still there. I hope that in Vedaconsulting they are working on solving the problem.

**Comment by Upperholme** [comment]
Update: In my case the difference seems to be that that the base page name is being included in the  URL on the Communications Preferences page, incorrectly:

My Communications Preferences page shows the URL to the privacy policy as:
https://domainname/civicrm/wp-content/plugins/files/civicrm/persist/contribute/privacy-policy-v1.pdf
(where the first /civicrm/ in this URL is the base page that Wordpress needs, as set at /wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fsetting%2Fuf&reset=1

If I visit https://domainname/wp-content/plugins/files/civicrm/persist/contribute/privacy-policy-v1.pdf instead, then the PDF file gets displayed as I would expect in the browser.

**Comment by Upperholme** [comment]
In my case I've fixed this by editing line 147 of CRM/Gdpr/Form/UpdatePreference.php (I'm using version 2.6 of the extension):
The original line:
`$tcLink = E::ts("<a href='%1' target='_blank'>%2</a>", array(1 => $gdprTermsConditionsUrl, 2 => $gdprTermsConditionslabel));`

and the edited line:
`$tcLink = E::ts("<a href='/%1' target='_blank'>%2</a>", array(1 => $gdprTermsConditionsUrl, 2 => $gdprTermsConditionslabel));`

i.e. I've simply added a forward slash at the beginning of the URL. This seems to work for me for the display of the Communications Preferences page for users visiting the page for the first time. I can't comment in the case where users have previously agreed a policy and it it has since been modified or sufficient time has passed such that a new approval is being sought.

**Comment by Upperholme** [comment]
This looks to be line 95 in the current dev version of the file.
