### ISSUE TITLE
Terms and Conditions Page remains permanently saving 

### ISSUE THREAD

**Issue by cuatrocento** [veda-consulting/uk.co.vedaconsulting.gdpr#92]
When we try to enable Terms and Conditions on every Contribution Page

**Comment by cuatrocento** [comment]
Yesterday, I could not save Terms & Conditions sections on a contribution page,  but now I can.
The problem now is that I do not see the Terms & Conditions section on the contributions front page  after saving it. I have tried changing the position of the checkbox. There are no visible errors.

Thanks for your answer. Sorry for my English.

**Comment by veda-consulting** [comment]
@cuatrocento ok could you confirm the version of CiviCRM, CMS and the GDPR extension? Thanks

**Comment by AlphaDE** [comment]
I have a similar problem on CiviCRM 5.2.0. After activating the module on an event registration page and after confirming both Privacy and T&C agreements, confirming all settings throws me back to the registration page with 

Please correct the following errors in the form below

* Terms & Conditions is a mandatory field.
* Terms & Conditions is a mandatory field.

and I cannot proceed. With that, the GDPR module is yet unuseable for me.



PHP Version: | 7.1.13
WordPress Version: | 4.9.6
Server Software: | Apache/2.4.33 (Debian)

**Comment by AlphaDE** [comment]
Problem is persisting with latest Wordpress, CiviCRM and GDPR versions,

**Comment by AlphaDE** [comment]
Same here, I created mandatory fields in event registrations... a pity that they do not even care...

**Comment by veda-consulting** [comment]
@AlphaDE I don't think it's fair to say we do not care. We are supporting this module without investment and are hoping members of the community step up to fix at least some of the on going issues.

We will take a look at the problem over the coming days.

**Comment by deepak-srivastava** [comment]
@AlphaDE @cuatrocento we couldn't reproduce the problem on latest civicrm (5.8.2), wordpress 5.0.2 and gdpr 2.7.

If you guys can ping me on [civicrm chat](https://chat.civicrm.org/civicrm) - i can try investigate the problem on your setup. 
My username "deepaks".

**Comment by AlphaDE** [comment]
I wrote you a PM there...

**Comment by deepak-srivastava** [comment]
UPDATE: 
@AlphaDE  allowed me have a look at their site. And it seems that for frontend pages (on wordpress) due to theme or js failures, 'terms and conditions' block is outside the form, which is causing values to not submit. Screenshot :
![image](https://user-images.githubusercontent.com/3448551/50402955-9d77bb00-0792-11e9-8702-a69b5cffd48c.png)
@AlphaDE  is about to look into their customization or setup civi in a way (possible a subdomain) that customization doesn't affect it, and report back.

**Comment by AlphaDE** [comment]
Good morning @deepak-srivastava
I just started to have a closer look... the jQuery errors you noticed were caused by the CiviCRM mobile plugin adding it's initializing code just before everything, consequently also before 

addLoadEvent = function(func){if(typeof jQuery!="undefined")jQuery(document).ready(func);else if(typeof wpOnload!='function'){wpOnload=func;}else{var oldonload=wpOnload;wpOnload=function(){oldonload();func();}}};

So the registration pages loads without script errors, nevertheless, the effect remains the same, the acknowlegement of T&C is not taken to the next page when registering for an event.

Back to square 1.

**Comment by deepak-srivastava** [comment]
UPDATE:
Checked with @AlphaDE again. Seems like its working when logged in but not when logged out (frontend pages). It seems like wordpress frontend pages are stripping out civicrm js.
Following screenshot shows the js files / resources that are missing for frontend pages, which is causing javscript to not work:
![image](https://user-images.githubusercontent.com/3448551/50479699-c3d66a00-09cf-11e9-8c3e-6d6f1d639d00.png)

**Comment by deepak-srivastava** [comment]
Cool that you figured it out and good to know. Might help others as well. Thanks.
